version: "3.9"
services:
  db:
    build: db/
  web:
    build: .
    ports:
      - "80:3000"
    volumes:
      - logvolume01:/var/log
    depends_on:
      - db
    tty: true
volumes:
  logvolume01: {}