export default [
    {taskID:"a001",
        taskName:"Main Task1",
        course:"Course1",
        parentID:"",
        hasSubtasks:true,
        desc:"Task 1 for Course1",
        deadline:"2020-12-30 16:00:00"
    },
    {taskID:"a002",
        taskName:"Subtask1",
        course:"Course1",
        parentID:"a001",
        hasSubtasks:true,
        desc:"Subtask 1 for Task1 in Course1",
        deadline:"2020-12-30 16:00:00"
    },
    {taskID:"b001",
        taskName:"Main Task2",
        course:"Course1",
        parentID:"",
        hasSubtasks:false,
        desc:"Task 2 for Course1",
        deadline:""
    },
    {taskID:"c001",
        taskName:"Main Task1",
        course:"Course2",
        parentID:"",
        hasSubtasks:false,
        desc:"Task 1 for Course2",
        deadline:"2020-12-30 16:00:00"
    },
    {taskID:"a003",
        taskName:"Tertiary1",
        course:"Course1",
        parentID:"a002",
        hasSubtasks:false,
        desc:"Sub task of Subtask 1",
        deadline:""
    },
    {taskID:"a004",
        taskName:"Subtask2",
        course:"Course1",
        parentID:"a001",
        hasSubtasks:false,
        desc:"Subtask 2 of Task 1",
        deadline:""
    }
];